### ISSUE TITLE
Escape sequences in strings

### ISSUE THREAD

**Issue by DrTobe** [DrTobe/bonglang#17]
`\n`, `\\`, `\"` should be supported at least.
Furthermore, we can discuss:
- Unicode-character input?
- `\t`
- `\r`

**Comment by mcgnus** [comment]
When do we need Unicode input? Is it really necessary or is it just nice to have?  We shouldn't make the parser more complicated than necessary.

**Comment by DrTobe** [comment]
Unicode input, for example with `\x...` or `\U...` would be the most general type of input which would allow us to do _anything_ with strings. If we omit this feature, there will be several things that we just can not do which would be a pity regarding the little effort that is needed to support it. Admittedly, if the file is utf-8 encoded, you just have to find out how to input unicode in your OS, but this seems to be the less intuitive way of doing it, at least in my opinion.

BTW, @mcgnus when will you implement this feature?

**Comment by mcgnus** [comment]
note to self: check for escape sequence and let python do the escaping into the string

**Comment by DrTobe** [comment]
Well, I've just decided to follow [Rust's leadership](https://doc.rust-lang.org/reference/tokens.html#characters-and-strings).
