### ISSUE TITLE
Move assignments from BinOp to its own ast node

### ISSUE THREAD

**Issue by DrTobe** [DrTobe/bonglang#18]
Currently, assignments are handled as part of binary operations (with `ast.BinOp`) and identified with `ast.BinOp.op == "="`. From my point of view, assignments are quite different from all the other binary operations, e.g. they support multiple comma-separated variables/expressions at once and have considerable side-effects why more type-checking is necessary. Therefore, they should be handled in their own `ast` node. This has the additional benefit that stricter type hinting is possible for assignments.

**Comment by mcgnus** [comment]
Closed with commit ec54cbb
