### ISSUE TITLE
Infinite loop in lexer

### ISSUE THREAD

**Issue by DrTobe** [DrTobe/bonglang#22]
```python
        if "\"" == c: # begin of a string
            lex = ""
            while not self.match("\""):
                lex += self.next()
```

When a file ends with an unfinished string, this loop will never finish.

What should we do here? Print an error message and ... do what? Return the string up to that point? Or return an EOF?

**Comment by ptrdtznr** [comment]
I would raise an exception (corrupted file)

**Comment by DrTobe** [comment]
I think so, too. I guess, this requires a change at all places where code is built/run because we do not check for lexer errors currently.
